array = [['Nearly Headless Nick', 15], ['Moaning Myrtle', 22], ['The Grey Lady', 45], ['The Bloody Baron', 77], ['The Headless Horseman', 54], ['Peeves', 31], ['The Fat Friar', 90], ['The Phantom', 62], ['The Woman in White', 88], ['The Whispering Ghost', 47], ['The Witch of the West', 30], ['The Shrieking Ghost', 72], ['The Old Man of the Sea', 13], ['The Black Shuck', 81], ['The White Lady', 66], ['The Spirit of the Forest', 35], ['The Wailing Woman', 99], ['The Haunted Knight', 28], ['The Spectral Cat', 11], ['The Wraith of the Moors', 73], ['The Haunting Apparition', 38], ['The Enigmatic Phantom', 82], ['The Lurking Shadow', 57], ['The Banshee', 21], ['The Restless Soul', 67], ['The Forgotten Ghost', 14], ['The Eternal Wanderer', 48], ['The Mysterious Veil', 79], ['The Lamenting Spirit', 53], ['The Lost Traveler', 94], ['The Foggy Figure', 60], ['The Ethereal Guide', 25], ['The Spectral Guardian', 17], ['The Echoing Voice', 83], ['The Cursed Apparition', 71], ['The Haunting Melody', 29], ['The Lamenting Echo', 42], ['The Flickering Light', 59], ['The Glimmering Shade', 36], ['The Silent Whisper', 78], ['The Wandering Shade', 41], ['The Grieving Spirit', 12], ['The Whispering Wind', 63], ['The Phantom Librarian', 98], ['The Lost Love', 75], ['The Timeless Spirit', 20], ['The Twilight Watcher', 46], ['The Celestial Ghost', 87], ['The Shattered Soul', 39], ['The Wandering Mind', 85], ['The Hollow Shade', 5], ['The Timid Wraith', 19], ['The Lonely Ghost', 44], ['The Ghostly Guardian', 69], ['The Eternal Wisp', 99], ['The Shadowed Specter', 8], ['The Weeping Ghost', 24], ['The Foggy Apparition', 33], ['The Phantasmagorical Figure', 55], ['The Ghostly Voice', 91], ['The Shimmering Spirit', 2], ['The Phantom of the Night', 26], ['The Glowing Specter', 76], ['The Enigmatic Shade', 10], ['The Timeless Wraith', 65], ['The Twilight Spirit', 37], ['The Flickering Flame', 4], ['The Ethereal Figure', 50], ['The Midnight Ghost', 61], ['The Shadowy Sentinel', 1], ['The Veiled Watcher', 97], ['The Apparition of Hope', 92], ['The Bewitched Spirit', 34], ['The Shadowed Knight', 3], ['The Whispering Spirit', 95], ['The Eclipsed Ghost', 16], ['The Wandering Phantasm', 99], ['The Shimmering Wisp', 40], ['The Dreaming Spirit', 58], ['The Lost Soul', 70], ['The Wistful Wraith', 9], ['The Forgotten Shade', 84], ['The Glimmering Ghost', 49], ['The Enchanted Spirit', 61], ['The Resonating Phantom', 88], ['The Ghost of Regret', 86], ['The Haunting Presence', 45], ['The Ethereal Guardian', 23], ['The Wandering Echo', 14], ['The Fading Shade', 72], ['The Echoing Spirit', 11], ['The Ghostly Scholar', 96], ['The Eternal Guardian', 52], ['The Luminous Shade', 68], ['The Celestial Wisp', 30], ['The Echoing Whisper', 65], ['The Radiant Spirit', 73], ['The Mournful Shade', 18], ['The Veiled Wraith', 64]]
for i in range(len(array)):
    for j in range(0, len(array)-i-1):
        if array[j][1] > array[j+1][1]:
            temp = array[j+1]
            array[j+1] = array[j]
            array[j] = temp

print(array[((len(array)+1)//2)-1][0])
